import { Metadata } from 'next';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { getPageBySlug, getPages } from '@/lib/wordpress';
import { getCanonicalUrl } from '@/lib/site-config';

// Reserved slugs that have dedicated Next.js pages - must not be generated by [slug]
const RESERVED_SLUGS = [
  'homepage',
  'portfolio',
  'about',
  'blog',
  'contact',
  'resume',
  'services',
  'loading',
  'maintenance',
];

/** Strip .html suffix (static export generates .html files; dev server may receive those requests) */
function normalizeSlug(raw: string): string {
  return raw.endsWith('.html') ? raw.slice(0, -5) : raw;
}

export async function generateStaticParams() {
  const pages = await getPages(100, 1).catch(() => []);
  const slugs = pages
    .filter((p) => !RESERVED_SLUGS.includes(p.slug))
    .flatMap((p) => [{ slug: p.slug }, { slug: `${p.slug}.html` }]);

  // Also generate .html variants for reserved slugs so requests like /about.html
  // don't crash with "missing param" (the page component will notFound() them)
  const reservedHtml = RESERVED_SLUGS.map((s) => ({ slug: `${s}.html` }));

  const all = [...slugs, ...reservedHtml];
  // Next.js static export requires at least one param when API fails
  if (all.length === 0) return [{ slug: '__no-pages__' }];
  return all;
}

interface PageProps {
  params: Promise<{
    slug: string;
  }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const rawSlug = (await params).slug;
  const slug = normalizeSlug(rawSlug);

  // Handle fallback slug or reserved slugs (they have their own routes)
  if (slug === '__no-pages__' || RESERVED_SLUGS.includes(slug)) {
    return {
      title: slug === '__no-pages__' ? 'Pages Unavailable' : 'Page Not Found',
    };
  }

  const page = await getPageBySlug(slug);

  if (!page) {
    return {
      title: 'Page Not Found',
    };
  }

  const featuredImage = page._embedded?.['wp:featuredmedia']?.[0];

  return {
    title: page.title.rendered.replace(/<[^>]*>/g, '').trim() || 'Page',
    description: page.excerpt.rendered.replace(/<[^>]*>/g, '').substring(0, 160),
    alternates: { canonical: getCanonicalUrl(`/${slug}`) },
    openGraph: {
      title: page.title.rendered,
      description: page.excerpt.rendered.replace(/<[^>]*>/g, '').substring(0, 160),
      images: featuredImage ? [featuredImage.source_url] : [],
    },
  };
}

export default async function Page({ params }: PageProps) {
  const rawSlug = (await params).slug;
  const slug = normalizeSlug(rawSlug);

  // Reserved slugs have dedicated routes — 404 if hit here (e.g. via .html suffix)
  if (RESERVED_SLUGS.includes(slug)) {
    notFound();
  }

  // Handle fallback slug when API fails
  if (slug === '__no-pages__') {
    return (
      <article className="max-w-4xl mx-auto px-4 py-16">
        <div className="text-center py-12">
          <p className="text-zinc-600 dark:text-zinc-400 text-lg">
            Pages are currently unavailable. Please try again later.
          </p>
        </div>
      </article>
    );
  }
  
  const page = await getPageBySlug(slug);

  if (!page) {
    notFound();
  }

  const featuredImage = page._embedded?.['wp:featuredmedia']?.[0];

  return (
    <article className="max-w-4xl mx-auto px-4 py-16">
      {/* Header */}
      <header className="mb-8">
        <h1 
          className="text-4xl md:text-5xl font-bold mb-4 text-black dark:text-white"
          dangerouslySetInnerHTML={{ __html: page.title.rendered }}
        />
      </header>

      {/* Featured Image */}
      {featuredImage?.source_url && (
        <div className="featured-image-write-in relative w-full aspect-video mb-8 rounded-lg">
          <Image
            src={featuredImage.source_url}
            alt={featuredImage.alt_text || page.title.rendered}
            fill
            className="object-cover"
            priority
          />
        </div>
      )}

      {/* Content */}
      <div 
        className="prose prose-lg dark:prose-invert max-w-none prose-headings:font-bold prose-a:text-blue-600 dark:prose-a:text-blue-400"
        dangerouslySetInnerHTML={{ __html: page.content.rendered }}
      />
    </article>
  );
}
